name: scattering_inverse_network
channels:
- pytorch
dependencies:
- python=3.5
- numpy=1.13.0
- scikit-learn=0.18.2
- jupyter=1.0.0
- numba=0.35.0
- tqdm
- pytorch=0.4
- pip:
    - librosa==0.5.1
    - kymatio==0.1
